#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            
            - pipe: sonarsource/sonarcloud-scan:1.2.1
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.3
              # variables:
              #   SONAR_TOKEN: '<string>'  # Optional
              #   EXTRA_ARGS: '<string>'  # Optional
              #   SONAR_SCANNER_OPTS: '<string>'  # Optional
              #   DEBUG: '<boolean>'  # Optional

